version: '3'

services:
  api:
    build: .
    restart: always
    depends_on:
      - mongo 
    environment:
      - PORT=8080
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DB=workouts
    ports:
      - 8080:8080
    command: ["./wait-for-it.sh", "mongo:27017", "--", "/go/bin/warmup-api"]
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    
