version: '3'

services:
  api:
    build: .
    restart: always
    depends_on:
      - mongo 
    environment:
      - PORT=8080
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=workout_app
      - MONGO_COLLECTION=workouts
    ports:
      - 8080:8080
    command: ["./wait-for-it.sh", "mongo:27017", "--", "/go/bin/warmup-api"]
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    
