pipeline {
  environment {
    registry = "mbchoa/warmup"
    registryCredential = 'dockerhub'
    dockerImage = ''
  }
  agent any
  stages {
    stage('Cloning Git') {
      steps {
        git 'https://github.com/mbchoa/warmup.git'
      }
    }
    stage('Building Web Image') {
      steps{
        script {
          dockerImage = docker.build("${registry}:${BUILD_NUMBER}", "./web") 
        }
      }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry('', registryCredential) {
            dockerImage.push()
          }
        }
      }
    }
  }
}
